const express = require('express')
const router = express.Router()

const indexRouter = require('./main')
const orderRouter = require('./orders')
const rolesRouter = require('./roles')
const agentsRouter = require('./agents')
const extrasRouter = require('./extras')
const productRouter = require('./products')
const customersRouter = require('./customers')
const authRouter = require('./auth')
const usersRouter = require('./users')
const dashboardRouter = require('./dashboard')
const markersRouter = require('./markers')
const menusRouter = require('./menus')
const operationsRouter = require('./operations')
const routesRouter = require('./routes')

router.use('/', indexRouter)
router.use('/orders', orderRouter)
router.use('/roles', rolesRouter)
router.use('/agents', agentsRouter)
router.use('/extras', extrasRouter)
router.use('/products', productRouter)
router.use('/customers', customersRouter)
router.use('/auth', authRouter)
router.use('/users', usersRouter)
router.use('/dashboard', dashboardRouter)
router.use('/markers', markersRouter)
router.use('/menus', menusRouter)
router.use('/operations', operationsRouter)
router.use('/routes', routesRouter)

module.exports = router
